package com.myspring.eium.hm.hm_p0040.vo;

import org.springframework.stereotype.Component;

@Component
public class HM_P0040VO {
String EMPLOYEE_TRAINING_CODE;
public String getEMPLOYEE_TRAINING_CODE() {
	return EMPLOYEE_TRAINING_CODE;
}
public void setEMPLOYEE_TRAINING_CODE(String eMPLOYEE_TRAINING_CODE) {
	EMPLOYEE_TRAINING_CODE = eMPLOYEE_TRAINING_CODE;
}
public String getEMPLOYEE_TRAINING_NAME() {
	return EMPLOYEE_TRAINING_NAME;
}
public void setEMPLOYEE_TRAINING_NAME(String eMPLOYEE_TRAINING_NAME) {
	EMPLOYEE_TRAINING_NAME = eMPLOYEE_TRAINING_NAME;
}
public String getEMPLOYEE_TRAINING_START_DATE() {
	return EMPLOYEE_TRAINING_START_DATE;
}
public void setEMPLOYEE_TRAINING_START_DATE(String eMPLOYEE_TRAINING_START_DATE) {
	EMPLOYEE_TRAINING_START_DATE = eMPLOYEE_TRAINING_START_DATE;
}
public String getEMPLOYEE_TRAINING_END_DATE() {
	return EMPLOYEE_TRAINING_END_DATE;
}
public void setEMPLOYEE_TRAINING_END_DATE(String eMPLOYEE_TRAINING_END_DATE) {
	EMPLOYEE_TRAINING_END_DATE = eMPLOYEE_TRAINING_END_DATE;
}
public String getEMPLOYEE_TRAINING_DATE_COUNT() {
	return EMPLOYEE_TRAINING_DATE_COUNT;
}
public void setEMPLOYEE_TRAINING_DATE_COUNT(String eMPLOYEE_TRAINING_DATE_COUNT) {
	EMPLOYEE_TRAINING_DATE_COUNT = eMPLOYEE_TRAINING_DATE_COUNT;
}
public String getEMPLOYEE_TRAINING_GOAL() {
	return EMPLOYEE_TRAINING_GOAL;
}
public void setEMPLOYEE_TRAINING_GOAL(String eMPLOYEE_TRAINING_GOAL) {
	EMPLOYEE_TRAINING_GOAL = eMPLOYEE_TRAINING_GOAL;
}
public String getEMPLOYEE_TRAINING_LOCATION() {
	return EMPLOYEE_TRAINING_LOCATION;
}
public void setEMPLOYEE_TRAINING_LOCATION(String eMPLOYEE_TRAINING_LOCATION) {
	EMPLOYEE_TRAINING_LOCATION = eMPLOYEE_TRAINING_LOCATION;
}
public String getEMPLOYEE_TRAINING_TEACHER() {
	return EMPLOYEE_TRAINING_TEACHER;
}
public void setEMPLOYEE_TRAINING_TEACHER(String eMPLOYEE_TRAINING_TEACHER) {
	EMPLOYEE_TRAINING_TEACHER = eMPLOYEE_TRAINING_TEACHER;
}
public String getEMPLOYEE_TRAINING_INSITUTION() {
	return EMPLOYEE_TRAINING_INSITUTION;
}
public void setEMPLOYEE_TRAINING_INSITUTION(String eMPLOYEE_TRAINING_INSITUTION) {
	EMPLOYEE_TRAINING_INSITUTION = eMPLOYEE_TRAINING_INSITUTION;
}
public String getEMPLOYEE_TRAINING_TIME() {
	return EMPLOYEE_TRAINING_TIME;
}
public void setEMPLOYEE_TRAINING_TIME(String eMPLOYEE_TRAINING_TIME) {
	EMPLOYEE_TRAINING_TIME = eMPLOYEE_TRAINING_TIME;
}
public String getEMPLOYEE_TRAINING_PEOPLE() {
	return EMPLOYEE_TRAINING_PEOPLE;
}
public void setEMPLOYEE_TRAINING_PEOPLE(String eMPLOYEE_TRAINING_PEOPLE) {
	EMPLOYEE_TRAINING_PEOPLE = eMPLOYEE_TRAINING_PEOPLE;
}
public String getEMPLOYEE_TRAINING_IN_OUT() {
	return EMPLOYEE_TRAINING_IN_OUT;
}
public void setEMPLOYEE_TRAINING_IN_OUT(String eMPLOYEE_TRAINING_IN_OUT) {
	EMPLOYEE_TRAINING_IN_OUT = eMPLOYEE_TRAINING_IN_OUT;
}
String EMPLOYEE_TRAINING_NAME;
String EMPLOYEE_TRAINING_START_DATE;
String EMPLOYEE_TRAINING_END_DATE;
String EMPLOYEE_TRAINING_DATE_COUNT;
String EMPLOYEE_TRAINING_GOAL;
String EMPLOYEE_TRAINING_LOCATION;
String EMPLOYEE_TRAINING_TEACHER;
String EMPLOYEE_TRAINING_INSITUTION;
String EMPLOYEE_TRAINING_TIME;
String EMPLOYEE_TRAINING_PEOPLE;
String EMPLOYEE_TRAINING_IN_OUT;
String EMPLOYEE_CODE;
String EMPLOYEE_NAME;
String DEPARTMENT_NAME;
public String getEMPLOYEE_CODE() {
	return EMPLOYEE_CODE;
}
public void setEMPLOYEE_CODE(String eMPLOYEE_CODE) {
	EMPLOYEE_CODE = eMPLOYEE_CODE;
}
public String getEMPLOYEE_NAME() {
	return EMPLOYEE_NAME;
}
public void setEMPLOYEE_NAME(String eMPLOYEE_NAME) {
	EMPLOYEE_NAME = eMPLOYEE_NAME;
}
public String getDEPARTMENT_NAME() {
	return DEPARTMENT_NAME;
}
public void setDEPARTMENT_NAME(String dEPARTMENT_NAME) {
	DEPARTMENT_NAME = dEPARTMENT_NAME;
}
public String getPOSITION_NAME() {
	return POSITION_NAME;
}
public void setPOSITION_NAME(String pOSITION_NAME) {
	POSITION_NAME = pOSITION_NAME;
}
String POSITION_NAME;
public String getATTENDENCE_SCORE() {
	return ATTENDENCE_SCORE;
}
public void setATTENDENCE_SCORE(String aTTENDENCE_SCORE) {
	ATTENDENCE_SCORE = aTTENDENCE_SCORE;
}
public String getATTITUDE_SCORE() {
	return ATTITUDE_SCORE;
}
public void setATTITUDE_SCORE(String aTTITUDE_SCORE) {
	ATTITUDE_SCORE = aTTITUDE_SCORE;
}
public String getSCORE() {
	return SCORE;
}
public void setSCORE(String sCORE) {
	SCORE = sCORE;
}
public String getASSESSMENT_DESC() {
	return ASSESSMENT_DESC;
}
public void setASSESSMENT_DESC(String aSSESSMENT_DESC) {
	ASSESSMENT_DESC = aSSESSMENT_DESC;
}
public String getCODE() {
	return CODE;
}
public void setCODE(String cODE) {
	CODE = cODE;
}
public String getTOTAL() {
	return TOTAL;
}
public void setTOTAL(String tOTAL) {
	TOTAL = tOTAL;
}
String ATTENDENCE_SCORE;
String ATTITUDE_SCORE;
String SCORE;
String ASSESSMENT_DESC;
String CODE;
String TOTAL;
String FINISH_YN;
public String getFINISH_YN() {
	return FINISH_YN;
}
public void setFINISH_YN(String fINISH_YN) {
	FINISH_YN = fINISH_YN;
}


}
